deployers:
  image:
    deployer_name: kubernetes
    connection:
      cacert: ''
      cert: ''
      host: ''
      key: ''
log:
  level: debug
logged_outputs:
  error:
    level: error
  success:
    level: debug
