---
deployer:
  connection:
    cacert: ''
    cert: ''
    host: https://api.tsebasti-lab.aws.rhperfscale.org:6443
    key: ''
  type: kubernetes
log:
  level: debug
logged_outputs:
  error:
    level: error
  success:
    level: debug
