input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        kubeconfig:
          display:
            description: The complete kubeconfig file as a string
            name: Kubeconfig file contents
          type:
            type_id: string
          required: true
        node_selector:
            display:
              description: kubernetes node name where the plugin must be deployed
            type:
              type_id: map
              values:
                type_id: string
              keys:
                type_id: string
            required: true
        sysbench_threads:
          display:
            description: The number of threads sysbench will run
            name: sysbench threads
          type:
            type_id: integer
        sysbench_events:
          display:
            description: The number of events sysbench will run
            name: sysbench events
          type:
            type_id: integer
        sysbench_runtime:
          display:
            description: The total runtime in seconds for the sysbench tests
            name: sysbench runtime seconds
          type:
            type_id: integer
        sysbench_forced_shutdown_time:
          display:
            description: Number of seconds to wait after the 'time' limit before forcing shutdown, or exclude parameter to disable forced shutdown
            name: sysbench runtime seconds
          type:
            type_id: integer
        sysbench_cpumaxprime:
          display:
            description: The upper limit of the number of prime numbers generated
            name: sysbench cpu max primes
          type:
            type_id: integer

steps:
  kubeconfig:
    plugin: quay.io/arcalot/arcaflow-plugin-kubeconfig:latest
    input:
      kubeconfig: !expr $.input.kubeconfig
  sysbench:
    plugin: quay.io/arcalot/arcaflow-plugin-sysbench:latest
    step: sysbenchcpu
    input:
      threads: !expr $.input.sysbench_threads
      events: !expr $.input.sysbench_events
      time: !expr $.input.sysbench_runtime
      forced-shutdown: !expr $.input.sysbench_forced_shutdown_time
      cpu-max-prime: !expr $.input.sysbench_cpumaxprime
    deploy:
      type: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:

        metadata:
          namespace: default
          labels:
            arcaflow: sysbench
        spec:
          nodeSelector: !expr $.input.node_selector
          pluginContainer:
            imagePullPolicy: Always
output:
  sysbench: !expr $.steps.sysbench.outputs.success
