
    Get Episodes from the Chaos ID.---
    tags:
      - ChaosAI API Results
    parameters:
      - name: chaosid
        in: path
        type: string
        required: true
        description: Chaos-ID
    responses:
      500:
        description: Error!
      200:
        description: Results for the given Chaos ID.
