kraken:
    kubeconfig_path: /root/.kube/config                    # Path to kubeconfig
    scenarios:  []                                           # List of policies/chaos scenarios to load
        #-    scenarios/etcd.yml
        #-    scenarios/openshift-kube-apiserver.yml
        #-    scenarios/openshift-apiserver.yml
    node_scenarios:
        -     nodeScenarios/node_scenario_example2.yml
cerberus:
    cerberus_enabled: False                                # Enable it when cerberus is previously installed
    cerberus_url:                                          # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go signal

tunings:
    iterations: 1
    daemon_mode: False
    wait_duration: 10                                      # Duration to wait between each chaos scenario
