version: v0.2.0
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        input_list:
          type:
            type_id: list
            items:
              id: SubRootObject
              type_id: ref
              namespace: $.steps.workload_loop.execute.inputs.items
steps:
  workload_loop:
    kind: foreach
    items: !expr $.input.input_list
    workflow: sub-workflow.yaml
    parallelism: 1000
outputs:
  success:
    workloads: !expr $.steps.workload_loop.outputs.success.data



