version: v0.2.0
input:
  root: RootObject
  objects:
    KubernetesTarget:
      id: KubernetesTarget
      properties:
        kubeconfig_path:
          type:
            type_id: string
    RootObject:
      id: RootObject
      properties:
        cpu_hog_enabled:
          type:
            type_id: bool
        pod_chaos_enabled:
          type:
            type_id: bool
        kubeburner_enabled:
          type:
            type_id: bool
        kubernetes_target:
          type:
            type_id: ref
            id: KubernetesTarget
        kubeburner_list:
          type:
            type_id: list
            items:
              type_id: ref
              id: KubeBurner
              namespace: $.steps.kubeburner_wf.execute.inputs.items
        pod_chaos_list:
          type:
            type_id: list
            items:
              type_id: ref
              id: KillPodConfig
              namespace: $.steps.pod_chaos_wf.execute.inputs.items
        hog_cpu_list:
          type:
            type_id: list
            items:
              type_id: ref
              id: HogCpuInput
              namespace: $.steps.hog_cpu_wf.execute.inputs.items

steps:
  kubeburner_wf:
    kind: foreach
    items: !expr 'bindConstants($.input.kubeburner_list, $.input.kubernetes_target)'
    workflow: subworkflows/kubeburner.yaml
    parallelism: 1
    enabled: !expr $.input.kubeburner_enabled
  pod_chaos_wf:
    kind: foreach
    items: !expr 'bindConstants($.input.pod_chaos_list, $.input.kubernetes_target)'
    workflow: subworkflows/pod-chaos.yaml
    parallelism: 1
    enabled: !expr $.input.pod_chaos_enabled
  hog_cpu_wf:
    kind: foreach
    items: !expr 'bindConstants($.input.hog_cpu_list, $.input.kubernetes_target)'
    workflow: subworkflows/cpu-hog.yaml
    parallelism: 1
    enabled: !expr $.input.cpu_hog_enabled

outputs:
  workflow_success:
    kubeburner: !ordisabled $.steps.kubeburner_wf.outputs.success
    pod_chaos: !ordisabled $.steps.pod_chaos_wf.outputs.success
    cpu_hog: !ordisabled $.steps.hog_cpu_wf.outputs.success
